[package]
name = "trusttunnel-settings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
trusttunnel-deeplink = { git = "https://github.com/TrustTunnel/TrustTunnel" }
