name: Lint Rust

env:
  RUST_CHANNEL: 1.85

on:
  push:
    branches:
      - "*"
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  rust-lint:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'skipci:')"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.RUST_CHANNEL }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_CHANNEL }}
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Lint Rust
        run: |
          make lint-rust
